keys:
  - &horse_felix age1vhkq8lq7zlq0l7mt6dqsuc3nv6hnnnszpq6xqp83xjyh7t9zay5syy72yn
  - &source_felix age10vhp2pu4hwehj5ta9z7celgjzk6xm4aauagwsruhsvrua80cvejs2jgjhj
  # ON REINSTALL: Run `sudo nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
  # on the target machine, then insert the output here as the new server key for that machine, und run
  # `sops updatekeys` for all files that were encrypted with the old key.
  - &server_junction age10lw7g8yq6vmul3d8gl0d6ampkeeghcmxtqmt7kguma5x3sfcmqcqzxyrg7
creation_rules:
  - path_regex: nixos/junction/secrets.yaml
    key_groups:
    - age:
      - *horse_felix
      - *source_felix
      - *server_junction
  - path_regex: tofu/secrets.env
    key_groups:
    - age:
      - *horse_felix
      - *source_felix