{ net, ... }:
{
  # This machine is exposed directly to the internet. I want to reduce the amount
  # of log lines that are generated by bots trying to break in, even though
  # the security benefit of fail2ban is limited.
  services.fail2ban = {
    enable = true;
    ignoreIP = [
      # Ensure that configuration issues in remote building don't lock me out
      net.home.subnet
      net.wireguard.subnet
    ];
    maxretry = 3;
    bantime = "5m"; # Might ban myself accidentally, so I don't want to start too high
    bantime-increment = {
      enable = true;
      factor = "2";
      maxtime = "48h";
      # Not strictly required, but a good idea in case I add multiple jails
      overalljails = true;
    };
  };
}
