# Enable a list of options
source $ZDOTDIR/keybinds.zsh

# Enable all autocompletions for nix-installed tools
for p in ${(z)NIX_PROFILES}; do
  fpath+=($p/share/zsh/site-functions $p/share/zsh/$ZSH_VERSION/functions $p/share/zsh/vendor-completions)
done

# Enable a list of options (after fpath was set, this is important for completions!)
source $ZDOTDIR/options.zsh

# Set history options
HISTSIZE=100000
HISTFILESIZE=200000
SAVEHIST=100000
HISTFILE=~/.cache/zsh/history
setopt appendhistory
# Ensure the history file is present
mkdir -p $(dirname $HISTFILE)
touch $HISTFILE

# Enable thefuck alias
if [[ $(command -v thefuck) ]]; then
  eval $(thefuck --alias)
fi

# Autojump needs to be sourced to work on Ubuntu
source $HOME/.nix-profile/share/autojump/autojump.zsh

# Source node version manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Source cargo
[ -s "$HOME/.cargo/env" ] && source $HOME/.cargo/env

# Source gcloud stuff if available
if [[ ! $(command -v gcloud) && -e "$HOME/Documents/Apps/google-cloud-sdk/" ]]; then
  source "$HOME/Documents/Apps/google-cloud-sdk/path.zsh.inc"
  source "$HOME/Documents/Apps/google-cloud-sdk/completion.zsh.inc"
fi

# Broot is better run as br for functionality reasons
[ -e "$HOME/.config/broot" ] && source $HOME/.config/broot/launcher/bash/br

# Source fzf
source $ZDOTDIR/fzf.zsh

# Make sure vim is the default editor
export EDITOR="$HOME/.nix-profile/bin/vim"
export VISUAL="$HOME/.nix-profile/bin/vim"

# Activate p10k
source $HOME/.nix-profile/share/zsh-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

# Enable seamless isolated environments in every project dir with asdf-vm and asdf-direnv
[[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc ]] ||  source ${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc
# Enable support for non-deterministic version numbers in .nvmrc for asdf
export ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY=latest_available
# Install some npm packages by default with asdf nodejs
export ASDF_NPM_DEFAULT_PACKAGES_FILE=$HOME/.config/asdf-default-npm-packages

# Let direnv hook into zsh. Used especially for nix
if [[ $(command -v direnv) ]]; then
  eval "$(direnv hook zsh)"
fi

