esphome:
  name: my-first-esp32

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret my-first-esp32_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "My-First-Esp32 Fallback Hotspot"
    password: "jQgkgeP65f1F"

captive_portal:
    
switch:
  - platform: gpio
    name: "Shelf status indicator"
    pin: GPIO5

binary_sensor:
  - platform: gpio
    name: "Shelf enabled button"
    pin:
      number: 10
      inverted: true
      mode:
        input: true
        pullup: true